### ISSUE TITLE
CSS Style is broken on Partners page

### ISSUE THREAD

**Issue by AlexandrUrita** [MitocGroup/www#129]
Steps to reproduce:
1. Navigate to www.mitocgroup.com
2. Navigate to Partners page

Expected result: CSS styles should not be broken

Actual result: CSS styles are broken![Screen Shot 2018-01-15 at 10.25.11.png](https://images.zenhubusercontent.com/58f86b8b51aa2c30577beb5e/98d9464d-1aff-4abc-88bb-ebcd48b99fad)

**Comment by AlexandrUrita** [comment]
Also on /Services page CSS style is broken

**Comment by eistrati** [comment]
@AlexandrUrita @ursuvlad works for me. can you please double check this issue?

**Comment by eistrati** [comment]
Checked.
