### ISSUE TITLE
Replace AWS badge with new one

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/www#138]
Here is the new badge:
[Badge.eps.zip](https://github.com/MitocGroup/www/files/1754458/Badge.eps.zip)

**Comment by avozicov** [comment]
Implemented 
<img width="1440" alt="screen shot 2018-07-31 at 11 41 17" src="https://user-images.githubusercontent.com/12330493/43448442-a7fada02-94b6-11e8-96bc-e24184aebb57.png">

**Comment by eistrati** [comment]
Checked.
