### ISSUE TITLE
Medium blog post doesn't appear on www.mitocgroup.com

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/www#140]
The following article is expected to be loaded on main page 
<img width="1440" alt="screen shot 2018-04-30 at 13 00 26" src="https://user-images.githubusercontent.com/12330493/39422720-415024ec-4c77-11e8-844a-fab50c374240.png">

Actual result:
- medium blogpost section is not updated 
<img width="1440" alt="screen shot 2018-04-30 at 13 00 19" src="https://user-images.githubusercontent.com/12330493/39422734-4ff99fc8-4c77-11e8-8fca-b60525e2f378.png">

**Comment by eistrati** [comment]
Checked.
