### ISSUE TITLE
Fix link name PROC-006

### ISSUE THREAD

**Issue by Dimitrioglo** [MitocGroup/www#149]
1.  Valid link https://github.com/MitocGroup/www/blob/master/process/PROD-006-issue-tracking.md
Please change to https://github.com/MitocGroup/www/blob/master/process/PROC-006-issue-tracking.md
screenshot https://imgur.com/a/cNb7Z4O
2. Importance : Blocking
3. Issue type: Enchancment

**Comment by eistrati** [comment]
Fixed.
